spring:

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://krimson701.cafe24.com:3306/krimson701?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: krimson701
    password: CRH8B*e2YUsbsQ9
  jpa:
    generate-ddl: true
    hibernate:
      dialect: MySQLInnoDBDialect
      ddl-auto: update # validate in prod
      cache:
        use_second_level_cache: true
        use_query_cache: false
    show-sql: true
  redis:
    host: 121.130.105.58
    port: 6379
kafka:
  server: 110.34.74.134:9092

server:
  port: 9090
